language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2/repository"
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - mvn clean package -DskipTests=true jacoco:report org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_NEW_TOKEN
