language: java
jdk: openjdk11
services:
  - docker

before_install:
  - docker build -t mongo .
  - docker run -d -p 127.0.0.1:27017:27017 mongo
  - docker ps -a
  
cache:
  directories:
    - "$HOME/.m2/repository"
after_success:
  - bash <(curl -s https://codecov.io/bash)
